#
# OCI Secrets Store CSI Driver Provider
# 
# Copyright (c) 2022 Oracle America, Inc. and its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
# 
# Daemonset manifest for OCI Secrets Store CSI Driver Provider.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
  name: oci-secrets-store-csi-driver-provider
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
    spec:
      serviceAccountName: oci-secrets-store-csi-driver-provider-sa
      containers:
        - name: oci-secrets-store-csi-driver-provider
          image: "{{ .Values.provider.image.repository }}:{{ .Values.provider.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///opt/provider/sockets/oci.sock
            - --endpoint-permissions={{ .Values.provider.endpointPermissions }}
            - --healthz-port=8098
            - --metrics-port=8198
            - --enable-pprof=true
            - --pprof-port=6060
          env:
            - name: OCI_RESOURCE_PRINCIPAL_VERSION
              value: "2.2"
            - name: OCI_RESOURCE_PRINCIPAL_REGION
              value: "us-ashburn-1" 
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          # Container should run as root to mount the hostPath volume and create Unix Domain Socket in that volume.
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: "/opt/provider/sockets"
              name: socket-volume
      volumes:
        - name: socket-volume
          hostPath:
            path: /var/run/secrets-store-csi-providers