apiVersion: v1
entries:
  oci-secrets-store-csi-driver-provider:
  - apiVersion: v2
    appVersion: 0.9.5
    created: "2023-07-10T10:27:12.916007269Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.3.3
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 081f6dc4c50defceed0389ae17d29b3b711c70e9387b9c8471f6a57104e4e662
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 0.9.4
    created: "2023-07-10T10:27:12.912449142Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.3.3
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: ba0a19e198ebb75bf7a3ee0b14312e3c411770dbf8d31ccb1f8e6402b0477647
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.9.4
    created: "2023-07-10T10:27:12.909394818Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 41fb007af7e8f7443eb71939b250e62bb07748eb0a7f1ec362232b6704316345
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 0.9.4
    created: "2023-07-10T10:27:12.907778006Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 3f4d2e46aef9b90a229f8bf4dcc8775ab1719d3e7963e8c4132879455d288bd6
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 0.9.3
    created: "2023-07-10T10:27:12.906159893Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: f8ac4037fa2b42b8b98f7c959b27a7da0ec42cdd3748c4238fb4da77ed62e0ab
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2023-07-10T10:27:12.904523081Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 8355d0344a198193e343a31c1fd6e6ae52a73c0505036bb2267cc53541f6cc55
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2023-07-10T10:27:12.900987154Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 10f5dc2a2ce14ee9a7d87e9482d76476427d71df2e9e35c96a1debb4217ba44c
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.5.tgz
    version: 0.2.5
generated: "2023-07-10T10:27:12.899113039Z"
