apiVersion: v1
entries:
  oci-secrets-store-csi-driver-provider:
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2023-02-15T00:24:11.456375+05:30"
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 8355d0344a198193e343a31c1fd6e6ae52a73c0505036bb2267cc53541f6cc55
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    urls:
    - https://oracle-samples.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2023-02-15T00:24:11.451457+05:30"
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 10f5dc2a2ce14ee9a7d87e9482d76476427d71df2e9e35c96a1debb4217ba44c
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    urls:
    - https://oracle-samples.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.5.tgz
    version: 0.2.5
generated: "2023-02-15T00:24:11.433681+05:30"
